name: G9 diário

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'
    - cron: '0 7 * * *'

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Run script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          PERDAS: ${{ secrets.PERDAS }}
          FADEQ: ${{ secrets.FADEQ }}
          AC: ${{ secrets.AC }}
          GGS: ${{ secrets.GGS }}
          TAR_VAZIO: ${{ secrets.TAR_VAZIO }}
          TAR_FV: ${{ secrets.TAR_FV }}
          EREDES_CSV_URL: ${{ secrets.EREDES_CSV_URL }}
          FORCE_RUN: 1
        run: python main.py
